
// OPEN AND CLOSE THE FIRST MODAL
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CHANGE_NAME = 'CHANGE_NAME'

// OPEN AND CLOSE CUSTOMIZATION MODAL
export const OPEN_CUSTOMIZE_CHARACTER = 'OPEN_CUSTOMIZE_CHARACTER'
export const CLOSE_CUSTOMIZE_CHARACTER = 'CLOSE_CUSTOMIZE_CHARACTER'

// ADD TO THE LIST (TO-DO,HABIT,DAILY TASK)
export const ADD_TO_LIST = 'ADD_TO_LIST'
export const REMOVE_FROM_LIST = 'REMOVE_FROM_LIST'
export const SET_TO_DO_VALUE = 'SET_TO_DO_VALUE'

// ACTION AFTER COMPLETING THE TASK
export const COMPLETE_ITEM = 'COMPLETE_ITEM'

// ADD VALUE TO STATS 
export const INCREASE_EXPERIENCE = 'INCREASE_EXPERIENCE'
export const INCREASE_COINS = 'INCREASE_COINS'

// REMOVE NOTIFICATION AFTER CERTAIN TIME
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

// OPEN ITEM SETTINGS
export const OPEN_SETTINGS = 'OPEN_SETTINGS'

// LEVEL UP
export const LEVEL_UP = 'LEVEL_UP'