
// OPEN AND CLOSE THE FIRST MODAL
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CHANGE_NAME = 'CHANGE_NAME'

// OPEN AND CLOSE CUSTOMIZATION MODAL
export const OPEN_CUSTOMIZE_CHARACTER = 'OPEN_CUSTOMIZE_CHARACTER'
export const CLOSE_CUSTOMIZE_CHARACTER = 'CLOSE_CUSTOMIZE_CHARACTER'

// OPEN AND CLOSE LEVEL UP MODAL
export const OPEN_LVL_MODAL = 'OPEN_LVL_MODAL'
export const CLOSE_LVL_MODAL = 'CLOSE_LVL_MODAL'

// OPEN AND CLOSE 0 HEALTH MODAL
export const OPEN_NO_HEALTH_MODAL = 'OPEN_NO_HEALTH_MODAL'
export const CLOSE_NO_HEALTH_MODAL = 'CLOSE_NO_HEALTH_MODAL'


// ADD TO THE LIST (TO-DO,HABIT,DAILY TASK)
export const ADD_TO_LIST = 'ADD_TO_LIST'
export const REMOVE_FROM_LIST = 'REMOVE_FROM_LIST'
export const SET_TO_DO_VALUE = 'SET_TO_DO_VALUE'

// ACTION AFTER COMPLETING THE TASK
export const COMPLETE_ITEM = 'COMPLETE_ITEM'

// CHECKOUT DAILY TASK
export const CHECK_OUT_DAILY_TASK = 'CHECK_OUT_DAILY_TASK'
// RESET CHECK OUT WHEN DAY IS OVER (AND KEEP DAILYCOUNTER VALUE)
export const RESET_CHECK_OUT = 'RESET_CHECK_OUT'

// ADD VALUE TO STATS 
export const INCREASE_EXPERIENCE = 'INCREASE_EXPERIENCE'
export const INCREASE_COINS = 'INCREASE_COINS'

// REMOVE VALUE FROM STATS
export const DECREASE_EXPERIENCE = 'DECREASE_EXPERIENCE'
export const DECREASE_COINS = 'DECREASE_COINS'


// SHOW NOTIFICATION
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'

// REMOVE NOTIFICATION AFTER CERTAIN TIME
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

// OPEN AND SHOW ITEM SETTINGS
export const OPEN_SETTINGS = 'OPEN_SETTINGS'
export const SHOW_SETTINGS_ICON = 'SHOW_SETTINGS_ICON'

// CLOSE ITEM SETTINGS
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS'

// LEVEL UP
export const LEVEL_UP = 'LEVEL_UP'

// INCREASE HABIT_LIST COUNTER
export const INCREASE_COUNTER = 'INCREASE_COUNTER'
// DECREASE HABIT_LIST COUNTER
export const DECREASE_COUNTER = 'DECREASE_COUNTER'

// DECREASE HEALTH
export const DECREASE_HEALTH = 'DECREASE_HEALTH'

// TO BOTTOM
export const TO_BOTTOM = 'TO_BOTTOM'

// SORT ITEMS IN THE SHOP
export const SORT_ITEMS = 'SORT_ITEMS'
export const OPTION_VALUE = 'OPTION_VALUE'

// EDIT TASK
export const SET_EDIT_TASK = 'SET_EDIT_TASK'
export const EDIT_NAME = 'EDIT_NAME'
export const EDIT = 'EDIT'

// Update THE DATE WHEN TASK WAS CREATED
export const UPDATE_DATE = 'UPDATE_DATE'
// RESET/CANCEL EDIT
export const RESET_EDIT = 'RESET_EDIT'
// SUBMIT EDIT
export const SUBMIT_EDIT = 'SUBMIT_EDIT'

// Set Character Name // Google Auth
export const SET_NAME = 'SET_NAME'
export const SET_PROFILE_PIC = 'SET_PROFILE_PIC'

// LOADING SCREEN
export const REMOVE_LOADING_SCREEN = 'REMOVE_LOADING_SCREEN'
export const ADD_LOADING_SCREEN = 'ADD_LOADING_SCREEN'